//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Departments/Department.proto
// Note: requires additional types generated from: Address.proto
// Note: requires additional types generated from: Timestamp.proto
// Note: requires additional types generated from: Departments/Routing.proto
namespace Diadoc.Api.Proto.Departments
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Department")]
  public partial class Department : global::ProtoBuf.IExtensible
  {
    public Department() {}
    
    private string _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private string _ParentDepartmentId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ParentDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ParentDepartmentId
    {
      get { return _ParentDepartmentId; }
      set { _ParentDepartmentId = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Abbreviation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Abbreviation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Abbreviation
    {
      get { return _Abbreviation; }
      set { _Abbreviation = value; }
    }

    private string _Kpp = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Kpp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Kpp
    {
      get { return _Kpp; }
      set { _Kpp = value; }
    }

    private Diadoc.Api.Proto.Address _Address = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Address Address
    {
      get { return _Address; }
      set { _Address = value; }
    }
    private Diadoc.Api.Proto.Departments.Routing _Routing;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Routing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Departments.Routing Routing
    {
      get { return _Routing; }
      set { _Routing = value; }
    }
    private Diadoc.Api.Proto.Timestamp _CreationTimestamp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"CreationTimestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Timestamp CreationTimestamp
    {
      get { return _CreationTimestamp; }
      set { _CreationTimestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}