//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Departments/DepartmentList.proto
// Note: requires additional types generated from: Departments/Department.proto
namespace Diadoc.Api.Proto.Departments
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DepartmentList")]
  public partial class DepartmentList : global::ProtoBuf.IExtensible
  {
    public DepartmentList() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Departments.Department> _Departments = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Departments.Department>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Departments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Departments.Department> Departments
    {
      get { return _Departments; }
    }
  
    private int _TotalCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TotalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TotalCount
    {
      get { return _TotalCount; }
      set { _TotalCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}