//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Recognition/Recognition.proto
namespace Diadoc.Api.Proto.Recognition
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Recognized")]
  public partial class Recognized : global::ProtoBuf.IExtensible
  {
    public Recognized() {}
    
    private string _RecognitionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RecognitionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RecognitionId
    {
      get { return _RecognitionId; }
      set { _RecognitionId = value; }
    }

    private string _ErrorMessage = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ErrorMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMessage
    {
      get { return _ErrorMessage; }
      set { _ErrorMessage = value; }
    }

    private string _FileName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }

    private Diadoc.Api.Proto.Recognition.RecognizedDocumentType _DocumentType = Diadoc.Api.Proto.Recognition.RecognizedDocumentType.UnknownRecognizedDocumentType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DocumentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Recognition.RecognizedDocumentType.UnknownRecognizedDocumentType)]
    public Diadoc.Api.Proto.Recognition.RecognizedDocumentType DocumentType
    {
      get { return _DocumentType; }
      set { _DocumentType = value; }
    }

    private byte[] _Content = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private Diadoc.Api.Proto.Recognition.RecognizedInvoice _Invoice = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Invoice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Recognition.RecognizedInvoice Invoice
    {
      get { return _Invoice; }
      set { _Invoice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecognizedInvoice")]
  public partial class RecognizedInvoice : global::ProtoBuf.IExtensible
  {
    public RecognizedInvoice() {}
    
    private string _MetadataJson;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MetadataJson", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MetadataJson
    {
      get { return _MetadataJson; }
      set { _MetadataJson = value; }
    }

    private string _ValidationErrorMessage = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ValidationErrorMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ValidationErrorMessage
    {
      get { return _ValidationErrorMessage; }
      set { _ValidationErrorMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RecognizedDocumentType")]
    public enum RecognizedDocumentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownRecognizedDocumentType", Value=-1)]
      UnknownRecognizedDocumentType = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Invoice", Value=1)]
      Invoice = 1
    }
  
}