//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Organizations/BlockStatus.proto
// Note: requires additional types generated from: Organizations/ManualBlockStatus.proto
// Note: requires additional types generated from: Organizations/AutoBlockStatus.proto
namespace Diadoc.Api.Proto.Organizations
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockStatus")]
  public partial class BlockStatus : global::ProtoBuf.IExtensible
  {
    public BlockStatus() {}
    
    private Diadoc.Api.Proto.Organizations.ManualBlockStatus _ManualBlockStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ManualBlockStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Organizations.ManualBlockStatus ManualBlockStatus
    {
      get { return _ManualBlockStatus; }
      set { _ManualBlockStatus = value; }
    }
    private Diadoc.Api.Proto.Organizations.AutoBlockStatus _AutoBlockStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AutoBlockStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Organizations.AutoBlockStatus AutoBlockStatus
    {
      get { return _AutoBlockStatus; }
      set { _AutoBlockStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}