//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Diadoc.Api.DataXml.Utd820 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UniversalTransferDocument {
        
        private ExtendedOrganizationInfo[] sellersField;
        
        private ExtendedOrganizationInfo[] buyersField;
        
        private UniversalTransferDocumentShipper[] shippersField;
        
        private ExtendedOrganizationInfo[] consigneesField;
        
        private object[] signersField;
        
        private PaymentDocumentInfo[] paymentDocumentsField;
        
        private AdditionalInfoId additionalInfoIdField;
        
        private InvoiceTable tableField;
        
        private TransferInfo transferInfoField;
        
        private ExtendedOrganizationInfo factorInfoField;
        
        private TransferBase820 mainAssignMonetaryClaimField;
        
        private UniversalTransferDocumentSellerInfoCircumPublicProc sellerInfoCircumPublicProcField;
        
        private UniversalTransferDocumentDocumentShipment[] documentShipmentsField;
        
        private UniversalTransferDocumentFunction functionField;
        
        private string approvedStructureAdditionalInfoFieldsField;
        
        private string documentNameField;
        
        private string documentDateField;
        
        private string documentNumberField;
        
        private string currencyField;
        
        private decimal currencyRateField;
        
        private bool currencyRateFieldSpecified;
        
        private string revisionDateField;
        
        private string revisionNumberField;
        
        private string documentCreatorField;
        
        private string documentCreatorBaseField;
        
        private string governmentContractInfoField;
        
        private UniversalTransferDocumentCircumFormatInvoice circumFormatInvoiceField;
        
        private bool circumFormatInvoiceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Seller", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ExtendedOrganizationInfo[] Sellers {
            get {
                return this.sellersField;
            }
            set {
                this.sellersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Buyer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ExtendedOrganizationInfo[] Buyers {
            get {
                return this.buyersField;
            }
            set {
                this.buyersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Shipper", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UniversalTransferDocumentShipper[] Shippers {
            get {
                return this.shippersField;
            }
            set {
                this.shippersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Consignee", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ExtendedOrganizationInfo[] Consignees {
            get {
                return this.consigneesField;
            }
            set {
                this.consigneesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SignerDetails", typeof(ExtendedSignerDetails_SellerTitle), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(SignerReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public object[] Signers {
            get {
                return this.signersField;
            }
            set {
                this.signersField = value;
            }
        }

        public UniversalTransferDocument UseSignerReferences(SignerReference[] signerReferences)
        {
            this.Signers = signerReferences;
            return this;
        }
        
        public UniversalTransferDocument UseSignerDetails(ExtendedSignerDetails_SellerTitle[] signerDetails)
        {
            this.Signers = signerDetails;
            return this;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PaymentDocumentInfo[] PaymentDocuments {
            get {
                return this.paymentDocumentsField;
            }
            set {
                this.paymentDocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdditionalInfoId AdditionalInfoId {
            get {
                return this.additionalInfoIdField;
            }
            set {
                this.additionalInfoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTable Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransferInfo TransferInfo {
            get {
                return this.transferInfoField;
            }
            set {
                this.transferInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtendedOrganizationInfo FactorInfo {
            get {
                return this.factorInfoField;
            }
            set {
                this.factorInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransferBase820 MainAssignMonetaryClaim {
            get {
                return this.mainAssignMonetaryClaimField;
            }
            set {
                this.mainAssignMonetaryClaimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UniversalTransferDocumentSellerInfoCircumPublicProc SellerInfoCircumPublicProc {
            get {
                return this.sellerInfoCircumPublicProcField;
            }
            set {
                this.sellerInfoCircumPublicProcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentShipment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UniversalTransferDocumentDocumentShipment[] DocumentShipments {
            get {
                return this.documentShipmentsField;
            }
            set {
                this.documentShipmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UniversalTransferDocumentFunction Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApprovedStructureAdditionalInfoFields {
            get {
                return this.approvedStructureAdditionalInfoFieldsField;
            }
            set {
                this.approvedStructureAdditionalInfoFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CurrencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyRateSpecified {
            get {
                return this.currencyRateFieldSpecified;
            }
            set {
                this.currencyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string RevisionNumber {
            get {
                return this.revisionNumberField;
            }
            set {
                this.revisionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentCreator {
            get {
                return this.documentCreatorField;
            }
            set {
                this.documentCreatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentCreatorBase {
            get {
                return this.documentCreatorBaseField;
            }
            set {
                this.documentCreatorBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GovernmentContractInfo {
            get {
                return this.governmentContractInfoField;
            }
            set {
                this.governmentContractInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UniversalTransferDocumentCircumFormatInvoice CircumFormatInvoice {
            get {
                return this.circumFormatInvoiceField;
            }
            set {
                this.circumFormatInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CircumFormatInvoiceSpecified {
            get {
                return this.circumFormatInvoiceFieldSpecified;
            }
            set {
                this.circumFormatInvoiceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedOrganizationInfo {
        
        private ExtendedOrganizationDetails_ManualFilling itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganizationDetails", typeof(ExtendedOrganizationDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("OrganizationReference", typeof(ExtendedOrganizationReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtendedOrganizationDetails_ManualFilling Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedOrganizationDetails : ExtendedOrganizationDetails_ManualFilling {
        
        private Address addressField;
        
        private string orgNameField;
        
        private string innField;
        
        private string kppField;
        
        private string fnsParticipantIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrgName {
            get {
                return this.orgNameField;
            }
            set {
                this.orgNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FnsParticipantId {
            get {
                return this.fnsParticipantIdField;
            }
            set {
                this.fnsParticipantIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressCode", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ForeignAddress", typeof(ForeignAddress), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("RussianAddress", typeof(RussianAddress), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignAddress {
        
        private string countryField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferBase820))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferBase {
        
        private string baseDocumentNameField;
        
        private string baseDocumentNumberField;
        
        private string baseDocumentDateField;
        
        private string baseDocumentInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseDocumentName {
            get {
                return this.baseDocumentNameField;
            }
            set {
                this.baseDocumentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseDocumentNumber {
            get {
                return this.baseDocumentNumberField;
            }
            set {
                this.baseDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseDocumentDate {
            get {
                return this.baseDocumentDateField;
            }
            set {
                this.baseDocumentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseDocumentInfo {
            get {
                return this.baseDocumentInfoField;
            }
            set {
                this.baseDocumentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferBase820 : TransferBase {
        
        private string baseDocumentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseDocumentId {
            get {
                return this.baseDocumentIdField;
            }
            set {
                this.baseDocumentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferInfo {
        
        private TransferBase820[] transferBasesField;
        
        private WaybillsWaybill[] waybillsField;
        
        private AdditionalInfoId additionalInfoIdField;
        
        private ExtendedOrganizationInfo carrierField;
        
        private Employee employeeField;
        
        private OtherIssuer otherIssuerField;
        
        private string operationInfoField;
        
        private string operationTypeField;
        
        private string transferDateField;
        
        private string transferStartDateField;
        
        private string transferEndDateField;
        
        private string transferTextInfoField;
        
        private string createdThingTransferDateField;
        
        private string createdThingInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TransferBase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransferBase820[] TransferBases {
            get {
                return this.transferBasesField;
            }
            set {
                this.transferBasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Waybill", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WaybillsWaybill[] Waybills {
            get {
                return this.waybillsField;
            }
            set {
                this.waybillsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdditionalInfoId AdditionalInfoId {
            get {
                return this.additionalInfoIdField;
            }
            set {
                this.additionalInfoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtendedOrganizationInfo Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Employee Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OtherIssuer OtherIssuer {
            get {
                return this.otherIssuerField;
            }
            set {
                this.otherIssuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperationInfo {
            get {
                return this.operationInfoField;
            }
            set {
                this.operationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperationType {
            get {
                return this.operationTypeField;
            }
            set {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferDate {
            get {
                return this.transferDateField;
            }
            set {
                this.transferDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferStartDate {
            get {
                return this.transferStartDateField;
            }
            set {
                this.transferStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferEndDate {
            get {
                return this.transferEndDateField;
            }
            set {
                this.transferEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferTextInfo {
            get {
                return this.transferTextInfoField;
            }
            set {
                this.transferTextInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreatedThingTransferDate {
            get {
                return this.createdThingTransferDateField;
            }
            set {
                this.createdThingTransferDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreatedThingInfo {
            get {
                return this.createdThingInfoField;
            }
            set {
                this.createdThingInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WaybillsWaybill {
        
        private string transferDocumentNumberField;
        
        private string transferDocumentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferDocumentNumber {
            get {
                return this.transferDocumentNumberField;
            }
            set {
                this.transferDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransferDocumentDate {
            get {
                return this.transferDocumentDateField;
            }
            set {
                this.transferDocumentDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomsDeclaration {
        
        private string countryField;
        
        private string declarationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeclarationNumber {
            get {
                return this.declarationNumberField;
            }
            set {
                this.declarationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceTable {
        
        private InvoiceTableItem[] itemField;
        
        private decimal totalWithVatExcludedField;
        
        private bool totalWithVatExcludedFieldSpecified;
        
        private decimal vatField;
        
        private bool vatFieldSpecified;
        
        private InvoiceTableWithoutVat withoutVatField;
        
        private decimal totalField;
        
        private bool totalFieldSpecified;
        
        private decimal totalNetField;
        
        private bool totalNetFieldSpecified;
        
        public InvoiceTable() {
            this.withoutVatField = InvoiceTableWithoutVat.False;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceTableItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalWithVatExcluded {
            get {
                return this.totalWithVatExcludedField;
            }
            set {
                this.totalWithVatExcludedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalWithVatExcludedSpecified {
            get {
                return this.totalWithVatExcludedFieldSpecified;
            }
            set {
                this.totalWithVatExcludedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatSpecified {
            get {
                return this.vatFieldSpecified;
            }
            set {
                this.vatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(InvoiceTableWithoutVat.False)]
        public InvoiceTableWithoutVat WithoutVat {
            get {
                return this.withoutVatField;
            }
            set {
                this.withoutVatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalNet {
            get {
                return this.totalNetField;
            }
            set {
                this.totalNetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetSpecified {
            get {
                return this.totalNetFieldSpecified;
            }
            set {
                this.totalNetFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceTableItem {
        
        private CustomsDeclaration[] customsDeclarationsField;
        
        private AdditionalInfo[] additionalInfosField;
        
        private InvoiceTableItemItemTracingInfo[] itemTracingInfosField;
        
        private InvoiceTableItemItemIdentificationNumber[] itemIdentificationNumbersField;
        
        private string productField;
        
        private string unitField;
        
        private string unitNameField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private decimal exciseField;
        
        private bool exciseFieldSpecified;
        
        private TaxRateWithTwentyPercentAndTaxedByAgent taxRateField;
        
        private decimal subtotalWithVatExcludedField;
        
        private bool subtotalWithVatExcludedFieldSpecified;
        
        private decimal vatField;
        
        private bool vatFieldSpecified;
        
        private InvoiceTableItemWithoutVat withoutVatField;
        
        private decimal subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private InvoiceTableItemItemMark itemMarkField;
        
        private bool itemMarkFieldSpecified;
        
        private string additionalPropertyField;
        
        private string itemVendorCodeField;
        
        private decimal itemToReleaseField;
        
        private bool itemToReleaseFieldSpecified;
        
        private string itemCharactField;
        
        private string itemArticleField;
        
        private string itemKindField;
        
        private string catalogCodeField;
        
        private string itemTypeCodeField;
        
        public InvoiceTableItem() {
            this.withoutVatField = InvoiceTableItemWithoutVat.False;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomsDeclaration[] CustomsDeclarations {
            get {
                return this.customsDeclarationsField;
            }
            set {
                this.customsDeclarationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AdditionalInfo[] AdditionalInfos {
            get {
                return this.additionalInfosField;
            }
            set {
                this.additionalInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemTracingInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceTableItemItemTracingInfo[] ItemTracingInfos {
            get {
                return this.itemTracingInfosField;
            }
            set {
                this.itemTracingInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemIdentificationNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceTableItemItemIdentificationNumber[] ItemIdentificationNumbers {
            get {
                return this.itemIdentificationNumbersField;
            }
            set {
                this.itemIdentificationNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Excise {
            get {
                return this.exciseField;
            }
            set {
                this.exciseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExciseSpecified {
            get {
                return this.exciseFieldSpecified;
            }
            set {
                this.exciseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TaxRateWithTwentyPercentAndTaxedByAgent TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubtotalWithVatExcluded {
            get {
                return this.subtotalWithVatExcludedField;
            }
            set {
                this.subtotalWithVatExcludedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalWithVatExcludedSpecified {
            get {
                return this.subtotalWithVatExcludedFieldSpecified;
            }
            set {
                this.subtotalWithVatExcludedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatSpecified {
            get {
                return this.vatFieldSpecified;
            }
            set {
                this.vatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(InvoiceTableItemWithoutVat.False)]
        public InvoiceTableItemWithoutVat WithoutVat {
            get {
                return this.withoutVatField;
            }
            set {
                this.withoutVatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InvoiceTableItemItemMark ItemMark {
            get {
                return this.itemMarkField;
            }
            set {
                this.itemMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemMarkSpecified {
            get {
                return this.itemMarkFieldSpecified;
            }
            set {
                this.itemMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AdditionalProperty {
            get {
                return this.additionalPropertyField;
            }
            set {
                this.additionalPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemVendorCode {
            get {
                return this.itemVendorCodeField;
            }
            set {
                this.itemVendorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ItemToRelease {
            get {
                return this.itemToReleaseField;
            }
            set {
                this.itemToReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemToReleaseSpecified {
            get {
                return this.itemToReleaseFieldSpecified;
            }
            set {
                this.itemToReleaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemCharact {
            get {
                return this.itemCharactField;
            }
            set {
                this.itemCharactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemArticle {
            get {
                return this.itemArticleField;
            }
            set {
                this.itemArticleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemKind {
            get {
                return this.itemKindField;
            }
            set {
                this.itemKindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CatalogCode {
            get {
                return this.catalogCodeField;
            }
            set {
                this.catalogCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemTypeCode {
            get {
                return this.itemTypeCodeField;
            }
            set {
                this.itemTypeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceTableItemItemTracingInfo {
        
        private string regNumberUnitField;
        
        private string unitField;
        
        private decimal quantityField;
        
        private string itemAddInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegNumberUnit {
            get {
                return this.regNumberUnitField;
            }
            set {
                this.regNumberUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemAddInfo {
            get {
                return this.itemAddInfoField;
            }
            set {
                this.itemAddInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InvoiceTableItemItemIdentificationNumber {
        
        private string[] unitField;
        
        private string[] packageIdField;
        
        private string transPackageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransPackageId {
            get {
                return this.transPackageIdField;
            }
            set {
                this.transPackageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum TaxRateWithTwentyPercentAndTaxedByAgent {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        WithoutVat,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0%")]
        Zero,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10%")]
        TenPercent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18%")]
        EighteenPercent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20%")]
        TwentyPercent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        TenFraction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        EighteenFraction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20/120")]
        TwentyFraction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("НДС исчисляется налоговым агентом")]
        TaxedByAgent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTableItemWithoutVat {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("true")]
        True,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("false")]
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTableItemItemMark {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Property,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Job,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Service,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        PropertyRights,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum InvoiceTableWithoutVat {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("true")]
        True,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("false")]
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaymentDocumentInfo {
        
        private string dateField;
        
        private string numberField;
        
        private decimal totalField;
        
        private bool totalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RussianAddress {
        
        private string zipCodeField;
        
        private string regionField;
        
        private string territoryField;
        
        private string cityField;
        
        private string localityField;
        
        private string streetField;
        
        private string buildingField;
        
        private string blockField;
        
        private string apartmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Territory {
            get {
                return this.territoryField;
            }
            set {
                this.territoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedOrganizationReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedOrganizationDetails))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedOrganizationDetails_ManualFilling {
        
        private OrganizationType orgTypeField;
        
        private string okopfField;
        
        private string okpoField;
        
        private string okdpField;
        
        private string phoneField;
        
        private string emailField;
        
        private string correspondentAccountField;
        
        private string bankAccountNumberField;
        
        private string bankNameField;
        
        private string bankIdField;
        
        private string departmentField;
        
        private string organizationAdditionalInfoField;
        
        private string organizationOrPersonInfoField;
        
        private string individualEntityRegistrationCertificateField;
        
        private string legalEntityIdField;
        
        private string shortOrgNameField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OrganizationType OrgType {
            get {
                return this.orgTypeField;
            }
            set {
                this.orgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Okopf {
            get {
                return this.okopfField;
            }
            set {
                this.okopfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Okpo {
            get {
                return this.okpoField;
            }
            set {
                this.okpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Okdp {
            get {
                return this.okdpField;
            }
            set {
                this.okdpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CorrespondentAccount {
            get {
                return this.correspondentAccountField;
            }
            set {
                this.correspondentAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrganizationAdditionalInfo {
            get {
                return this.organizationAdditionalInfoField;
            }
            set {
                this.organizationAdditionalInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrganizationOrPersonInfo {
            get {
                return this.organizationOrPersonInfoField;
            }
            set {
                this.organizationOrPersonInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndividualEntityRegistrationCertificate {
            get {
                return this.individualEntityRegistrationCertificateField;
            }
            set {
                this.individualEntityRegistrationCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LegalEntityId {
            get {
                return this.legalEntityIdField;
            }
            set {
                this.legalEntityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortOrgName {
            get {
                return this.shortOrgNameField;
            }
            set {
                this.shortOrgNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum OrganizationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        LegalEntity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        IndividualEntity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        ForeignEntity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        PhysicalEntity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedOrganizationReference : ExtendedOrganizationDetails_ManualFilling {
        
        private string boxIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BoxId {
            get {
                return this.boxIdField;
            }
            set {
                this.boxIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UniversalTransferDocumentShipper {
        
        private ExtendedOrganizationDetails_ManualFilling itemField;
        
        private UniversalTransferDocumentShipperSameAsSeller sameAsSellerField;
        
        public UniversalTransferDocumentShipper() {
            this.sameAsSellerField = UniversalTransferDocumentShipperSameAsSeller.False;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganizationDetails", typeof(ExtendedOrganizationDetails), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("OrganizationReference", typeof(ExtendedOrganizationReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtendedOrganizationDetails_ManualFilling Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UniversalTransferDocumentShipperSameAsSeller.False)]
        public UniversalTransferDocumentShipperSameAsSeller SameAsSeller {
            get {
                return this.sameAsSellerField;
            }
            set {
                this.sameAsSellerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UniversalTransferDocumentShipperSameAsSeller {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("true")]
        True,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("false")]
        False,
    }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UniversalTransferDocumentSellerInfoCircumPublicProc {
        
        private string dateStateContractField;
        
        private string numberStateContractField;
        
        private string personalAccountSellerField;
        
        private string sellerBudjetClassCodeField;
        
        private string sellerTargetCodeField;
        
        private string sellerTreasuryCodeField;
        
        private string sellerTreasuryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateStateContract {
            get {
                return this.dateStateContractField;
            }
            set {
                this.dateStateContractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumberStateContract {
            get {
                return this.numberStateContractField;
            }
            set {
                this.numberStateContractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PersonalAccountSeller {
            get {
                return this.personalAccountSellerField;
            }
            set {
                this.personalAccountSellerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SellerBudjetClassCode {
            get {
                return this.sellerBudjetClassCodeField;
            }
            set {
                this.sellerBudjetClassCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SellerTargetCode {
            get {
                return this.sellerTargetCodeField;
            }
            set {
                this.sellerTargetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SellerTreasuryCode {
            get {
                return this.sellerTreasuryCodeField;
            }
            set {
                this.sellerTreasuryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SellerTreasuryName {
            get {
                return this.sellerTreasuryNameField;
            }
            set {
                this.sellerTreasuryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UniversalTransferDocumentDocumentShipment {
        
        private string nameField;
        
        private string numberField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UniversalTransferDocumentFunction {
        
        /// <remarks/>
        СЧФ,
        
        /// <remarks/>
        ДОП,
        
        /// <remarks/>
        СЧФДОП,
    }
    
    /// <remarks>
    /// Обстоятельства формирования счета-фактуры, применяемого при расчетах по налогу на добавленную стоимость
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UniversalTransferDocumentCircumFormatInvoice {
        
        /// <remarks>
        /// Cчет-фактура, выставляемый при реализации товаров (работ, услуг), передаче имущественных прав 
        /// </remarks>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        ItemsRealization,
        
        /// <remarks>
        /// Счет-фактура, выставляемый при получении оплаты, частичной оплаты в счет предстоящих
        /// поставок товаров (выполнения работ, оказания услуг), передачи имущественных прав 
        /// </remarks>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        PaymentsRecieve,
        
        /// <remarks>
        /// Счет-фактура, применяемый в случае реализации комиссионером (агентом, экспедитором, застройщиком или заказчиком, выполняющим функции застройщика)
        /// двум и более покупателям (приобретения у двух и более продавцов) товаров (работ, услуг), имущественных прав от своего имени
        /// </remarks>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        AgentSchema,
    }


