//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2.11.0.0")]
[assembly: AssemblyFileVersion("2.11.1-dev")]
[assembly: AssemblyInformationalVersion("2.11.1-dev")]

