//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Events/ResolutionInfo.proto
// Note: requires additional types generated from: ResolutionType.proto
namespace Diadoc.Api.Proto.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResolutionInfo")]
  public partial class ResolutionInfo : global::ProtoBuf.IExtensible
  {
    public ResolutionInfo() {}
    

    private Diadoc.Api.Proto.ResolutionType _ResolutionType = Diadoc.Api.Proto.ResolutionType.UnknownResolutionType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ResolutionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.ResolutionType.UnknownResolutionType)]
    public Diadoc.Api.Proto.ResolutionType ResolutionType
    {
      get { return _ResolutionType; }
      set { _ResolutionType = value; }
    }
    private string _Author;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Author", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Author
    {
      get { return _Author; }
      set { _Author = value; }
    }

    private string _InitialRequestId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"InitialRequestId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string InitialRequestId
    {
      get { return _InitialRequestId; }
      set { _InitialRequestId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}