//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Documents/UnilateralDocument.proto
// Note: requires additional types generated from: Documents/ReceiptStatus.proto
namespace Diadoc.Api.Proto.Documents.UnilateralDocument
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProformaInvoiceMetadata")]
  public partial class ProformaInvoiceMetadata : global::ProtoBuf.IExtensible
  {
    public ProformaInvoiceMetadata() {}
    

    private Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus _DocumentStatus = Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus.UnknownUnilateralDocumentStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DocumentStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus.UnknownUnilateralDocumentStatus)]
    public Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus DocumentStatus
    {
      get { return _DocumentStatus; }
      set { _DocumentStatus = value; }
    }
    private string _Total;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Total", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Total
    {
      get { return _Total; }
      set { _Total = value; }
    }

    private string _Vat = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Vat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Vat
    {
      get { return _Vat; }
      set { _Vat = value; }
    }

    private string _Grounds = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Grounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Grounds
    {
      get { return _Grounds; }
      set { _Grounds = value; }
    }

    private Diadoc.Api.Proto.Documents.ReceiptStatus _ReceiptStatus = Diadoc.Api.Proto.Documents.ReceiptStatus.UnknownReceiptStatus;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ReceiptStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.ReceiptStatus.UnknownReceiptStatus)]
    public Diadoc.Api.Proto.Documents.ReceiptStatus ReceiptStatus
    {
      get { return _ReceiptStatus; }
      set { _ReceiptStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceDetailsMetadata")]
  public partial class ServiceDetailsMetadata : global::ProtoBuf.IExtensible
  {
    public ServiceDetailsMetadata() {}
    
    private Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus _DocumentStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DocumentStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.Documents.UnilateralDocument.UnilateralDocumentStatus DocumentStatus
    {
      get { return _DocumentStatus; }
      set { _DocumentStatus = value; }
    }
    private Diadoc.Api.Proto.Documents.ReceiptStatus _ReceiptStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ReceiptStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.Documents.ReceiptStatus ReceiptStatus
    {
      get { return _ReceiptStatus; }
      set { _ReceiptStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UnilateralDocumentStatus")]
    public enum UnilateralDocumentStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownUnilateralDocumentStatus", Value=0)]
      UnknownUnilateralDocumentStatus = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Outbound", Value=1)]
      Outbound = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OutboundWaitingForSenderSignature", Value=4)]
      OutboundWaitingForSenderSignature = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OutboundInvalidSenderSignature", Value=5)]
      OutboundInvalidSenderSignature = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Inbound", Value=2)]
      Inbound = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Internal", Value=3)]
      Internal = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InternalWaitingForSenderSignature", Value=6)]
      InternalWaitingForSenderSignature = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InternalInvalidSenderSignature", Value=7)]
      InternalInvalidSenderSignature = 7
    }
  
}