//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Employees/Subscriptions/Subscription.proto
namespace Diadoc.Api.Proto.Employees.Subscriptions
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EmployeeSubscriptions")]
  public partial class EmployeeSubscriptions : global::ProtoBuf.IExtensible
  {
    public EmployeeSubscriptions() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription> _Subscriptions = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Subscriptions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription> Subscriptions
    {
      get { return _Subscriptions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscriptionsToUpdate")]
  public partial class SubscriptionsToUpdate : global::ProtoBuf.IExtensible
  {
    public SubscriptionsToUpdate() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription> _Subscriptions = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Subscriptions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Employees.Subscriptions.Subscription> Subscriptions
    {
      get { return _Subscriptions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Subscription")]
  public partial class Subscription : global::ProtoBuf.IExtensible
  {
    public Subscription() {}
    
    private string _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private bool _IsSubscribed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IsSubscribed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsSubscribed
    {
      get { return _IsSubscribed; }
      set { _IsSubscribed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}