//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Workflows/ParticipantType.proto
namespace Diadoc.Api.Proto.Workflows.ParticipantType
{
    [global::ProtoBuf.ProtoContract(Name=@"ParticipantType")]
    public enum ParticipantType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Unknown", Value=0)]
      Unknown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Sender", Value=1)]
      Sender = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proxy", Value=2)]
      Proxy = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Recipient", Value=3)]
      Recipient = 3
    }
  
}