//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DocflowStatusV3.proto
namespace Diadoc.Api.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DocflowStatusV3")]
  public partial class DocflowStatusV3 : global::ProtoBuf.IExtensible
  {
    public DocflowStatusV3() {}
    
    private Diadoc.Api.Proto.DocflowStatusModelV3 _PrimaryStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PrimaryStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.DocflowStatusModelV3 PrimaryStatus
    {
      get { return _PrimaryStatus; }
      set { _PrimaryStatus = value; }
    }

    private Diadoc.Api.Proto.DocflowStatusModelV3 _SecondaryStatus = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SecondaryStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.DocflowStatusModelV3 SecondaryStatus
    {
      get { return _SecondaryStatus; }
      set { _SecondaryStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DocflowStatusModelV3")]
  public partial class DocflowStatusModelV3 : global::ProtoBuf.IExtensible
  {
    public DocflowStatusModelV3() {}
    

    private string _Severity = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Severity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Severity
    {
      get { return _Severity; }
      set { _Severity = value; }
    }

    private string _StatusText = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"StatusText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string StatusText
    {
      get { return _StatusText; }
      set { _StatusText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}