//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ExternalServiceAuthInfo.proto
namespace Diadoc.Api.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExternalServiceAuthInfo")]
  public partial class ExternalServiceAuthInfo : global::ProtoBuf.IExtensible
  {
    public ExternalServiceAuthInfo() {}
    

    private string _ServiceUserId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServiceUserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ServiceUserId
    {
      get { return _ServiceUserId; }
      set { _ServiceUserId = value; }
    }

    private string _Thumbprint = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Thumbprint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Thumbprint
    {
      get { return _Thumbprint; }
      set { _Thumbprint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}