//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResolutionRequestType.proto
namespace Diadoc.Api.Proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ResolutionRequestType")]
    public enum ResolutionRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownResolutionRequestType", Value=-1)]
      UnknownResolutionRequestType = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ApprovementRequest", Value=0)]
      ApprovementRequest = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignatureRequest", Value=1)]
      SignatureRequest = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ApprovementSignatureRequest", Value=2)]
      ApprovementSignatureRequest = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Custom", Value=3)]
      Custom = 3
    }
  
}