//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResolutionRouteList.proto
namespace Diadoc.Api.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResolutionRouteList")]
  public partial class ResolutionRouteList : global::ProtoBuf.IExtensible
  {
    public ResolutionRouteList() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.ResolutionRoute> _ResolutionRoutes = new global::System.Collections.Generic.List<Diadoc.Api.Proto.ResolutionRoute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ResolutionRoutes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.ResolutionRoute> ResolutionRoutes
    {
      get { return _ResolutionRoutes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResolutionRoute")]
  public partial class ResolutionRoute : global::ProtoBuf.IExtensible
  {
    public ResolutionRoute() {}
    
    private string _RouteId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RouteId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RouteId
    {
      get { return _RouteId; }
      set { _RouteId = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}