//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SecurityEventList.proto
namespace Diadoc.Api.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecurityEventList")]
  public partial class SecurityEventList : global::ProtoBuf.IExtensible
  {
    public SecurityEventList() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.SecurityEvent> _Events = new global::System.Collections.Generic.List<Diadoc.Api.Proto.SecurityEvent>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.SecurityEvent> Events
    {
      get { return _Events; }
    }
  

    private string _LastIndexKey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LastIndexKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LastIndexKey
    {
      get { return _LastIndexKey; }
      set { _LastIndexKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecurityEvent")]
  public partial class SecurityEvent : global::ProtoBuf.IExtensible
  {
    public SecurityEvent() {}
    
    private string _EventId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EventId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EventId
    {
      get { return _EventId; }
      set { _EventId = value; }
    }
    private Diadoc.Api.Proto.SecurityEventType _EventType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.SecurityEventType EventType
    {
      get { return _EventType; }
      set { _EventType = value; }
    }
    private Diadoc.Api.Proto.SecurityEventTarget _Target;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.SecurityEventTarget Target
    {
      get { return _Target; }
      set { _Target = value; }
    }
    private long _TimestampTicks;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TimestampTicks", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long TimestampTicks
    {
      get { return _TimestampTicks; }
      set { _TimestampTicks = value; }
    }
    private string _Details;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Details
    {
      get { return _Details; }
      set { _Details = value; }
    }
    private string _IndexKey;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"IndexKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IndexKey
    {
      get { return _IndexKey; }
      set { _IndexKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecurityEventTarget")]
  public partial class SecurityEventTarget : global::ProtoBuf.IExtensible
  {
    public SecurityEventTarget() {}
    
    private Diadoc.Api.Proto.SecurityEventTargetType _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.SecurityEventTargetType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private Diadoc.Api.Proto.DocumentTarget _Document = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Document", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.DocumentTarget Document
    {
      get { return _Document; }
      set { _Document = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DocumentTarget")]
  public partial class DocumentTarget : global::ProtoBuf.IExtensible
  {
    public DocumentTarget() {}
    
    private string _LetterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LetterId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LetterId
    {
      get { return _LetterId; }
      set { _LetterId = value; }
    }
    private string _DocumentId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DocumentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DocumentId
    {
      get { return _DocumentId; }
      set { _DocumentId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SecurityEventTargetType")]
    public enum SecurityEventTargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownTargetType", Value=0)]
      UnknownTargetType = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Document", Value=1)]
      Document = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SecurityEventType")]
    public enum SecurityEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownEventType", Value=0)]
      UnknownEventType = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MalwareDetected", Value=1)]
      MalwareDetected = 1
    }
  
}