//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TemplateTransformationChangeType.proto
namespace Diadoc.Api.Proto
{
    [global::ProtoBuf.ProtoContract(Name=@"TemplateTransformationChangeType")]
    public enum TemplateTransformationChangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownTemplateTransformationChange", Value=0)]
      UnknownTemplateTransformationChange = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignatureRejection", Value=1)]
      SignatureRejection = 1
    }
  
}