//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Certificates/CertificateSubjectType.proto
namespace Diadoc.Api.Proto.Certificates
{
    [global::ProtoBuf.ProtoContract(Name=@"CertificateSubjectType")]
    public enum CertificateSubjectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownCertificateSubjectType", Value=0)]
      UnknownCertificateSubjectType = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LegalEntity", Value=1)]
      LegalEntity = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IndividualEntity", Value=2)]
      IndividualEntity = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PhysicalPerson", Value=3)]
      PhysicalPerson = 3
    }
  
}