//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CounteragentGroups/CounteragentGroupToCreate.proto
// Note: requires additional types generated from: CounteragentGroups/DepartmentsInGroup.proto
namespace Diadoc.Api.Proto.CounteragentGroups
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CounteragentGroupToCreate")]
  public partial class CounteragentGroupToCreate : global::ProtoBuf.IExtensible
  {
    public CounteragentGroupToCreate() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup _Departments = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Departments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments
    {
      get { return _Departments; }
      set { _Departments = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}