//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Docflow/AttachmentV3.proto
// Note: requires additional types generated from: Docflow/Attachment.proto
// Note: requires additional types generated from: Content.proto
// Note: requires additional types generated from: Timestamp.proto
// Note: requires additional types generated from: SignatureVerificationResult.proto
namespace Diadoc.Api.Proto.Docflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignatureV3")]
  public partial class SignatureV3 : global::ProtoBuf.IExtensible
  {
    public SignatureV3() {}
    
    private Diadoc.Api.Proto.Docflow.Entity _Cms;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Cms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Docflow.Entity Cms
    {
      get { return _Cms; }
      set { _Cms = value; }
    }

    private Diadoc.Api.Proto.Docflow.Entity _CadesT = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CadesT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.Entity CadesT
    {
      get { return _CadesT; }
      set { _CadesT = value; }
    }
    private string _SignerBoxId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SignerBoxId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SignerBoxId
    {
      get { return _SignerBoxId; }
      set { _SignerBoxId = value; }
    }
    private string _SignerDepartmentId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SignerDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SignerDepartmentId
    {
      get { return _SignerDepartmentId; }
      set { _SignerDepartmentId = value; }
    }
    private bool _IsValid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"IsValid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsValid
    {
      get { return _IsValid; }
      set { _IsValid = value; }
    }

    private Diadoc.Api.Proto.SignatureVerificationResult _VerificationResult = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"VerificationResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.SignatureVerificationResult VerificationResult
    {
      get { return _VerificationResult; }
      set { _VerificationResult = value; }
    }

    private Diadoc.Api.Proto.Timestamp _DeliveredAt = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"DeliveredAt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp DeliveredAt
    {
      get { return _DeliveredAt; }
      set { _DeliveredAt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignedAttachmentV3")]
  public partial class SignedAttachmentV3 : global::ProtoBuf.IExtensible
  {
    public SignedAttachmentV3() {}
    
    private Diadoc.Api.Proto.Docflow.Attachment _Attachment;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Attachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Docflow.Attachment Attachment
    {
      get { return _Attachment; }
      set { _Attachment = value; }
    }

    private Diadoc.Api.Proto.Docflow.SignatureV3 _Signature = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.SignatureV3 Signature
    {
      get { return _Signature; }
      set { _Signature = value; }
    }

    private Diadoc.Api.Proto.Docflow.Entity _Comment = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.Entity Comment
    {
      get { return _Comment; }
      set { _Comment = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}