//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Docflow/DocumentWithDocflow.proto
// Note: requires additional types generated from: Timestamp.proto
// Note: requires additional types generated from: DocumentId.proto
// Note: requires additional types generated from: ForwardDocumentEvent.proto
// Note: requires additional types generated from: Docflow/Docflow.proto
// Note: requires additional types generated from: Docflow/DocumentInfo.proto
namespace Diadoc.Api.Proto.Docflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DocumentWithDocflow")]
  public partial class DocumentWithDocflow : global::ProtoBuf.IExtensible
  {
    public DocumentWithDocflow() {}
    

    private Diadoc.Api.Proto.DocumentId _DocumentId = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DocumentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.DocumentId DocumentId
    {
      get { return _DocumentId; }
      set { _DocumentId = value; }
    }

    private string _LastEventId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LastEventId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LastEventId
    {
      get { return _LastEventId; }
      set { _LastEventId = value; }
    }

    private Diadoc.Api.Proto.Timestamp _LastEventTimestamp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LastEventTimestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp LastEventTimestamp
    {
      get { return _LastEventTimestamp; }
      set { _LastEventTimestamp = value; }
    }

    private Diadoc.Api.Proto.Docflow.DocumentInfo _DocumentInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DocumentInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.DocumentInfo DocumentInfo
    {
      get { return _DocumentInfo; }
      set { _DocumentInfo = value; }
    }

    private Diadoc.Api.Proto.Docflow.Docflow _Docflow = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Docflow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.Docflow Docflow
    {
      get { return _Docflow; }
      set { _Docflow = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> _InitialDocumentIds = new global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId>();
    [global::ProtoBuf.ProtoMember(6, Name=@"InitialDocumentIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> InitialDocumentIds
    {
      get { return _InitialDocumentIds; }
    }
  
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> _SubordinateDocumentIds = new global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId>();
    [global::ProtoBuf.ProtoMember(7, Name=@"SubordinateDocumentIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> SubordinateDocumentIds
    {
      get { return _SubordinateDocumentIds; }
    }
  
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent> _ForwardDocumentEvents = new global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent>();
    [global::ProtoBuf.ProtoMember(8, Name=@"ForwardDocumentEvents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent> ForwardDocumentEvents
    {
      get { return _ForwardDocumentEvents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}