//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Docflow/OuterDocflowV5.proto
// Note: requires additional types generated from: Docflow/DocflowV3.proto
namespace Diadoc.Api.Proto.Docflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OuterDocflowV5")]
  public partial class OuterDocflowV5 : global::ProtoBuf.IExtensible
  {
    public OuterDocflowV5() {}
    
    private string _DocflowNamedId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DocflowNamedId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DocflowNamedId
    {
      get { return _DocflowNamedId; }
      set { _DocflowNamedId = value; }
    }
    private string _ParentEntityId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ParentEntityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ParentEntityId
    {
      get { return _ParentEntityId; }
      set { _ParentEntityId = value; }
    }
    private string _LatestStatusEntityId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LatestStatusEntityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LatestStatusEntityId
    {
      get { return _LatestStatusEntityId; }
      set { _LatestStatusEntityId = value; }
    }
    private string _DocflowFriendlyName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DocflowFriendlyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DocflowFriendlyName
    {
      get { return _DocflowFriendlyName; }
      set { _DocflowFriendlyName = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.StatusEntity> _StatusEntities = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.StatusEntity>();
    [global::ProtoBuf.ProtoMember(5, Name=@"StatusEntities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.StatusEntity> StatusEntities
    {
      get { return _StatusEntities; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}