//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Docflow/OutOfWorkflowUniversalMessageDocflow.proto
// Note: requires additional types generated from: Docflow/UniversalMessageAttachmentDocflow.proto
namespace Diadoc.Api.Proto.Docflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OutOfWorkflowUniversalMessageDocflow")]
  public partial class OutOfWorkflowUniversalMessageDocflow : global::ProtoBuf.IExtensible
  {
    public OutOfWorkflowUniversalMessageDocflow() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.UniversalMessageAttachmentDocflow> _Messages = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.UniversalMessageAttachmentDocflow>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.UniversalMessageAttachmentDocflow> Messages
    {
      get { return _Messages; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}