//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Docflow/RevocationDocflowV5.proto
// Note: requires additional types generated from: Timestamp.proto
// Note: requires additional types generated from: Documents/Document.proto
// Note: requires additional types generated from: Documents/DocumentParticipantV2.proto
// Note: requires additional types generated from: Docflow/AttachmentV3.proto
// Note: requires additional types generated from: Docflow/DocflowV4.proto
// Note: requires additional types generated from: Docflow/DocflowV3.proto
// Note: requires additional types generated from: Docflow/DocumentInfoV5.proto
// Note: requires additional types generated from: Docflow/RoamingNotification.proto
// Note: requires additional types generated from: Docflow/ResolutionDocflowV5.proto
namespace Diadoc.Api.Proto.Docflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevocationRequestDocflowV5")]
  public partial class RevocationRequestDocflowV5 : global::ProtoBuf.IExtensible
  {
    public RevocationRequestDocflowV5() {}
    
    private Diadoc.Api.Proto.Docflow.SignedAttachmentV3 _RevocationRequest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RevocationRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Docflow.SignedAttachmentV3 RevocationRequest
    {
      get { return _RevocationRequest; }
      set { _RevocationRequest = value; }
    }

    private Diadoc.Api.Proto.Timestamp _SentAt = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SentAt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp SentAt
    {
      get { return _SentAt; }
      set { _SentAt = value; }
    }

    private Diadoc.Api.Proto.Timestamp _DeliveredAt = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"DeliveredAt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp DeliveredAt
    {
      get { return _DeliveredAt; }
      set { _DeliveredAt = value; }
    }

    private Diadoc.Api.Proto.Docflow.RoamingNotification _RoamingNotification = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"RoamingNotification", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.RoamingNotification RoamingNotification
    {
      get { return _RoamingNotification; }
      set { _RoamingNotification = value; }
    }

    private string _PlainText = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"PlainText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PlainText
    {
      get { return _PlainText; }
      set { _PlainText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevocationResponseDocflowV5")]
  public partial class RevocationResponseDocflowV5 : global::ProtoBuf.IExtensible
  {
    public RevocationResponseDocflowV5() {}
    
    private Diadoc.Api.Proto.Documents.DocumentParticipantV2 _Participant;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Participant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Documents.DocumentParticipantV2 Participant
    {
      get { return _Participant; }
      set { _Participant = value; }
    }
    private bool _IsFinished;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IsFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsFinished
    {
      get { return _IsFinished; }
      set { _IsFinished = value; }
    }

    private Diadoc.Api.Proto.Docflow.SignatureV3 _Signature = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.SignatureV3 Signature
    {
      get { return _Signature; }
      set { _Signature = value; }
    }

    private Diadoc.Api.Proto.Docflow.SignatureRejectionDocflowV4 _Rejection = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Rejection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.SignatureRejectionDocflowV4 Rejection
    {
      get { return _Rejection; }
      set { _Rejection = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevocationDocflowV5")]
  public partial class RevocationDocflowV5 : global::ProtoBuf.IExtensible
  {
    public RevocationDocflowV5() {}
    
    private bool _IsFinished;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"IsFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsFinished
    {
      get { return _IsFinished; }
      set { _IsFinished = value; }
    }
    private Diadoc.Api.Proto.Docflow.RevocationRequestDocflowV5 _RevocationRequest;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RevocationRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Docflow.RevocationRequestDocflowV5 RevocationRequest
    {
      get { return _RevocationRequest; }
      set { _RevocationRequest = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.RevocationResponseDocflowV5> _RevocationResponse = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.RevocationResponseDocflowV5>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RevocationResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.RevocationResponseDocflowV5> RevocationResponse
    {
      get { return _RevocationResponse; }
    }
  
    private Diadoc.Api.Proto.Documents.DocumentParticipantV2 _Initiator;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Initiator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Diadoc.Api.Proto.Documents.DocumentParticipantV2 Initiator
    {
      get { return _Initiator; }
      set { _Initiator = value; }
    }
    private Diadoc.Api.Proto.Documents.RevocationStatus _RevocationStatus;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"RevocationStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.Documents.RevocationStatus RevocationStatus
    {
      get { return _RevocationStatus; }
      set { _RevocationStatus = value; }
    }

    private Diadoc.Api.Proto.Docflow.ResolutionDocflowV5 _Resolution = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Resolution", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Docflow.ResolutionDocflowV5 Resolution
    {
      get { return _Resolution; }
      set { _Resolution = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.OuterDocflowEntities> _OuterDocflowEntities = new global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.OuterDocflowEntities>();
    [global::ProtoBuf.ProtoMember(7, Name=@"OuterDocflowEntities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.Docflow.OuterDocflowEntities> OuterDocflowEntities
    {
      get { return _OuterDocflowEntities; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}