//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KeyValueStorage/KeyValueStorage.proto
namespace Diadoc.Api.Proto.KeyValueStorage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyValueStorageEntry")]
  public partial class KeyValueStorageEntry : global::ProtoBuf.IExtensible
  {
    public KeyValueStorageEntry() {}
    
    private string _Key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private string _Value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyValueStorageApiGetRequest")]
  public partial class KeyValueStorageApiGetRequest : global::ProtoBuf.IExtensible
  {
    public KeyValueStorageApiGetRequest() {}
    
    private readonly global::System.Collections.Generic.List<string> _Keys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Keys
    {
      get { return _Keys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyValueStorageApiGetResponse")]
  public partial class KeyValueStorageApiGetResponse : global::ProtoBuf.IExtensible
  {
    public KeyValueStorageApiGetResponse() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry> _Entries = new global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry> Entries
    {
      get { return _Entries; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyValueStorageApiPutRequest")]
  public partial class KeyValueStorageApiPutRequest : global::ProtoBuf.IExtensible
  {
    public KeyValueStorageApiPutRequest() {}
    
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry> _Entries = new global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry> Entries
    {
      get { return _Entries; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}