//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("1.37.0.0")]
[assembly: AssemblyFileVersion("1.37.2-dev")]
[assembly: AssemblyInformationalVersion("1.37.2-dev")]

