//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Documents/Document.proto
// Note: requires additional types generated from: Content.proto
// Note: requires additional types generated from: DocumentId.proto
// Note: requires additional types generated from: CustomDataItem.proto
// Note: requires additional types generated from: DocumentType.proto
// Note: requires additional types generated from: DocumentDirection.proto
// Note: requires additional types generated from: Documents/AcceptanceCertificateDocument.proto
// Note: requires additional types generated from: Documents/BilateralDocument.proto
// Note: requires additional types generated from: Documents/InvoiceDocument.proto
// Note: requires additional types generated from: Documents/NonformalizedDocument.proto
// Note: requires additional types generated from: Documents/UnilateralDocument.proto
// Note: requires additional types generated from: Documents/UniversalTransferDocument.proto
// Note: requires additional types generated from: ResolutionTarget.proto
// Note: requires additional types generated from: ForwardDocumentEvent.proto
namespace Diadoc.Api.Proto.Documents
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Document")]
  public partial class Document : global::ProtoBuf.IExtensible
  {
    public Document() {}
    

    private string _IndexKey = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IndexKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IndexKey
    {
      get { return _IndexKey; }
      set { _IndexKey = value; }
    }
    private string _MessageId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MessageId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MessageId
    {
      get { return _MessageId; }
      set { _MessageId = value; }
    }
    private string _EntityId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EntityId
    {
      get { return _EntityId; }
      set { _EntityId = value; }
    }
    private long _CreationTimestampTicks;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"CreationTimestampTicks", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long CreationTimestampTicks
    {
      get { return _CreationTimestampTicks; }
      set { _CreationTimestampTicks = value; }
    }

    private string _CounteragentBoxId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"CounteragentBoxId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CounteragentBoxId
    {
      get { return _CounteragentBoxId; }
      set { _CounteragentBoxId = value; }
    }

    private Diadoc.Api.Proto.DocumentType _DocumentType = Diadoc.Api.Proto.DocumentType.UnknownDocumentType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"DocumentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.DocumentType.UnknownDocumentType)]
    public Diadoc.Api.Proto.DocumentType DocumentType
    {
      get { return _DocumentType; }
      set { _DocumentType = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> _InitialDocumentIds = new global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId>();
    [global::ProtoBuf.ProtoMember(7, Name=@"InitialDocumentIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> InitialDocumentIds
    {
      get { return _InitialDocumentIds; }
    }
  
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> _SubordinateDocumentIds = new global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId>();
    [global::ProtoBuf.ProtoMember(8, Name=@"SubordinateDocumentIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.DocumentId> SubordinateDocumentIds
    {
      get { return _SubordinateDocumentIds; }
    }
  

    private Diadoc.Api.Proto.Content _Content = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Content Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private string _FileName = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }

    private string _DocumentDate = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"DocumentDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DocumentDate
    {
      get { return _DocumentDate; }
      set { _DocumentDate = value; }
    }

    private string _DocumentNumber = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"DocumentNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DocumentNumber
    {
      get { return _DocumentNumber; }
      set { _DocumentNumber = value; }
    }

    private Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata _NonformalizedDocumentMetadata = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"NonformalizedDocumentMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata NonformalizedDocumentMetadata
    {
      get { return _NonformalizedDocumentMetadata; }
      set { _NonformalizedDocumentMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceMetadata _InvoiceMetadata = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"InvoiceMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceMetadata InvoiceMetadata
    {
      get { return _InvoiceMetadata; }
      set { _InvoiceMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.TrustConnectionRequestMetadata _TrustConnectionRequestMetadata = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"TrustConnectionRequestMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.TrustConnectionRequestMetadata TrustConnectionRequestMetadata
    {
      get { return _TrustConnectionRequestMetadata; }
      set { _TrustConnectionRequestMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata _Torg12Metadata = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Torg12Metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata Torg12Metadata
    {
      get { return _Torg12Metadata; }
      set { _Torg12Metadata = value; }
    }

    private Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceRevisionMetadata _InvoiceRevisionMetadata = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"InvoiceRevisionMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceRevisionMetadata InvoiceRevisionMetadata
    {
      get { return _InvoiceRevisionMetadata; }
      set { _InvoiceRevisionMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceCorrectionMetadata _InvoiceCorrectionMetadata = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"InvoiceCorrectionMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceCorrectionMetadata InvoiceCorrectionMetadata
    {
      get { return _InvoiceCorrectionMetadata; }
      set { _InvoiceCorrectionMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceCorrectionRevisionMetadata _InvoiceCorrectionRevisionMetadata = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"InvoiceCorrectionRevisionMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.InvoiceDocument.InvoiceCorrectionRevisionMetadata InvoiceCorrectionRevisionMetadata
    {
      get { return _InvoiceCorrectionRevisionMetadata; }
      set { _InvoiceCorrectionRevisionMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.AcceptanceCertificateDocument.AcceptanceCertificateMetadata _AcceptanceCertificateMetadata = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"AcceptanceCertificateMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.AcceptanceCertificateDocument.AcceptanceCertificateMetadata AcceptanceCertificateMetadata
    {
      get { return _AcceptanceCertificateMetadata; }
      set { _AcceptanceCertificateMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UnilateralDocument.ProformaInvoiceMetadata _ProformaInvoiceMetadata = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"ProformaInvoiceMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UnilateralDocument.ProformaInvoiceMetadata ProformaInvoiceMetadata
    {
      get { return _ProformaInvoiceMetadata; }
      set { _ProformaInvoiceMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata _XmlTorg12Metadata = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"XmlTorg12Metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata XmlTorg12Metadata
    {
      get { return _XmlTorg12Metadata; }
      set { _XmlTorg12Metadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata _XmlAcceptanceCertificateMetadata = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"XmlAcceptanceCertificateMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata XmlAcceptanceCertificateMetadata
    {
      get { return _XmlAcceptanceCertificateMetadata; }
      set { _XmlAcceptanceCertificateMetadata = value; }
    }

    private bool _IsDeleted = (bool)false;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"IsDeleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool IsDeleted
    {
      get { return _IsDeleted; }
      set { _IsDeleted = value; }
    }

    private string _DepartmentId = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"DepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DepartmentId
    {
      get { return _DepartmentId; }
      set { _DepartmentId = value; }
    }

    private bool _IsTest = (bool)false;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"IsTest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool IsTest
    {
      get { return _IsTest; }
      set { _IsTest = value; }
    }

    private string _FromDepartmentId = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"FromDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FromDepartmentId
    {
      get { return _FromDepartmentId; }
      set { _FromDepartmentId = value; }
    }

    private string _ToDepartmentId = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"ToDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ToDepartmentId
    {
      get { return _ToDepartmentId; }
      set { _ToDepartmentId = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.PriceListMetadata _PriceListMetadata = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"PriceListMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.PriceListMetadata PriceListMetadata
    {
      get { return _PriceListMetadata; }
      set { _PriceListMetadata = value; }
    }

    private string _CustomDocumentId = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"CustomDocumentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CustomDocumentId
    {
      get { return _CustomDocumentId; }
      set { _CustomDocumentId = value; }
    }

    private Diadoc.Api.Proto.Documents.ResolutionStatus _ResolutionStatus = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"ResolutionStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.ResolutionStatus ResolutionStatus
    {
      get { return _ResolutionStatus; }
      set { _ResolutionStatus = value; }
    }

    private Diadoc.Api.Proto.Documents.RevocationStatus _RevocationStatus = Diadoc.Api.Proto.Documents.RevocationStatus.UnknownRevocationStatus;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"RevocationStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.RevocationStatus.UnknownRevocationStatus)]
    public Diadoc.Api.Proto.Documents.RevocationStatus RevocationStatus
    {
      get { return _RevocationStatus; }
      set { _RevocationStatus = value; }
    }

    private long _SendTimestampTicks = default(long);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"SendTimestampTicks", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long SendTimestampTicks
    {
      get { return _SendTimestampTicks; }
      set { _SendTimestampTicks = value; }
    }

    private long _DeliveryTimestampTicks = default(long);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"DeliveryTimestampTicks", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long DeliveryTimestampTicks
    {
      get { return _DeliveryTimestampTicks; }
      set { _DeliveryTimestampTicks = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent> _ForwardDocumentEvents = new global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent>();
    [global::ProtoBuf.ProtoMember(35, Name=@"ForwardDocumentEvents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.ForwardDocumentEvent> ForwardDocumentEvents
    {
      get { return _ForwardDocumentEvents; }
    }
  

    private Diadoc.Api.Proto.Documents.BilateralDocument.BilateralDocumentMetadata _ReconciliationActMetadata = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"ReconciliationActMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.BilateralDocumentMetadata ReconciliationActMetadata
    {
      get { return _ReconciliationActMetadata; }
      set { _ReconciliationActMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.ContractMetadata _ContractMetadata = null;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"ContractMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.ContractMetadata ContractMetadata
    {
      get { return _ContractMetadata; }
      set { _ContractMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata _Torg13Metadata = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"Torg13Metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.BasicDocumentMetadata Torg13Metadata
    {
      get { return _Torg13Metadata; }
      set { _Torg13Metadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UnilateralDocument.ServiceDetailsMetadata _ServiceDetailsMetadata = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"ServiceDetailsMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UnilateralDocument.ServiceDetailsMetadata ServiceDetailsMetadata
    {
      get { return _ServiceDetailsMetadata; }
      set { _ServiceDetailsMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.RoamingNotificationStatus _RoamingNotificationStatus = Diadoc.Api.Proto.Documents.RoamingNotificationStatus.UnknownRoamingNotificationStatus;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"RoamingNotificationStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.RoamingNotificationStatus.UnknownRoamingNotificationStatus)]
    public Diadoc.Api.Proto.Documents.RoamingNotificationStatus RoamingNotificationStatus
    {
      get { return _RoamingNotificationStatus; }
      set { _RoamingNotificationStatus = value; }
    }

    private bool _HasCustomPrintForm = (bool)false;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"HasCustomPrintForm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool HasCustomPrintForm
    {
      get { return _HasCustomPrintForm; }
      set { _HasCustomPrintForm = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem> _CustomData = new global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem>();
    [global::ProtoBuf.ProtoMember(44, Name=@"CustomData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem> CustomData
    {
      get { return _CustomData; }
    }
  

    private string _PacketId = "";
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"PacketId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PacketId
    {
      get { return _PacketId; }
      set { _PacketId = value; }
    }

    private Diadoc.Api.Proto.DocumentDirection _DocumentDirection = Diadoc.Api.Proto.DocumentDirection.UnknownDocumentDirection;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"DocumentDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.DocumentDirection.UnknownDocumentDirection)]
    public Diadoc.Api.Proto.DocumentDirection DocumentDirection
    {
      get { return _DocumentDirection; }
      set { _DocumentDirection = value; }
    }

    private long _LastModificationTimestampTicks = default(long);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"LastModificationTimestampTicks", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long LastModificationTimestampTicks
    {
      get { return _LastModificationTimestampTicks; }
      set { _LastModificationTimestampTicks = value; }
    }

    private bool _IsEncryptedContent = default(bool);
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"IsEncryptedContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsEncryptedContent
    {
      get { return _IsEncryptedContent; }
      set { _IsEncryptedContent = value; }
    }

    private Diadoc.Api.Proto.Documents.SenderSignatureStatus _SenderSignatureStatus = Diadoc.Api.Proto.Documents.SenderSignatureStatus.UnknownSenderSignatureStatus;
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"SenderSignatureStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.SenderSignatureStatus.UnknownSenderSignatureStatus)]
    public Diadoc.Api.Proto.Documents.SenderSignatureStatus SenderSignatureStatus
    {
      get { return _SenderSignatureStatus; }
      set { _SenderSignatureStatus = value; }
    }

    private Diadoc.Api.Proto.Documents.BilateralDocument.SupplementaryAgreementMetadata _SupplementaryAgreementMetadata = null;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"SupplementaryAgreementMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.BilateralDocument.SupplementaryAgreementMetadata SupplementaryAgreementMetadata
    {
      get { return _SupplementaryAgreementMetadata; }
      set { _SupplementaryAgreementMetadata = value; }
    }

    private bool _IsRead = (bool)false;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"IsRead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool IsRead
    {
      get { return _IsRead; }
      set { _IsRead = value; }
    }

    private string _RoamingNotificationStatusDescription = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"RoamingNotificationStatusDescription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoamingNotificationStatusDescription
    {
      get { return _RoamingNotificationStatusDescription; }
      set { _RoamingNotificationStatusDescription = value; }
    }

    private bool _PacketIsLocked = (bool)false;
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"PacketIsLocked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool PacketIsLocked
    {
      get { return _PacketIsLocked; }
      set { _PacketIsLocked = value; }
    }

    private Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata _PriceListAgreementMetadata = null;
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"PriceListAgreementMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata PriceListAgreementMetadata
    {
      get { return _PriceListAgreementMetadata; }
      set { _PriceListAgreementMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata _CertificateRegistryMetadata = null;
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"CertificateRegistryMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.NonformalizedDocument.NonformalizedDocumentMetadata CertificateRegistryMetadata
    {
      get { return _CertificateRegistryMetadata; }
      set { _CertificateRegistryMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentMetadata _UniversalTransferDocumentMetadata = null;
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"UniversalTransferDocumentMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentMetadata UniversalTransferDocumentMetadata
    {
      get { return _UniversalTransferDocumentMetadata; }
      set { _UniversalTransferDocumentMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentRevisionMetadata _UniversalTransferDocumentRevisionMetadata = null;
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"UniversalTransferDocumentRevisionMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentRevisionMetadata UniversalTransferDocumentRevisionMetadata
    {
      get { return _UniversalTransferDocumentRevisionMetadata; }
      set { _UniversalTransferDocumentRevisionMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalCorrectionDocumentMetadata _UniversalCorrectionDocumentMetadata = null;
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"UniversalCorrectionDocumentMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalCorrectionDocumentMetadata UniversalCorrectionDocumentMetadata
    {
      get { return _UniversalCorrectionDocumentMetadata; }
      set { _UniversalCorrectionDocumentMetadata = value; }
    }

    private Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalCorrectionDocumentRevisionMetadata _UniversalCorrectionDocumentRevisionMetadata = null;
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"UniversalCorrectionDocumentRevisionMetadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Documents.UniversalTransferDocument.UniversalCorrectionDocumentRevisionMetadata UniversalCorrectionDocumentRevisionMetadata
    {
      get { return _UniversalCorrectionDocumentRevisionMetadata; }
      set { _UniversalCorrectionDocumentRevisionMetadata = value; }
    }

    private string _ResolutionRouteId = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"ResolutionRouteId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ResolutionRouteId
    {
      get { return _ResolutionRouteId; }
      set { _ResolutionRouteId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResolutionStatus")]
  public partial class ResolutionStatus : global::ProtoBuf.IExtensible
  {
    public ResolutionStatus() {}
    

    private Diadoc.Api.Proto.Documents.ResolutionStatusType _Type = Diadoc.Api.Proto.Documents.ResolutionStatusType.UnknownResolutionStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.Documents.ResolutionStatusType.UnknownResolutionStatus)]
    public Diadoc.Api.Proto.Documents.ResolutionStatusType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private Diadoc.Api.Proto.ResolutionTarget _Target = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.ResolutionTarget Target
    {
      get { return _Target; }
      set { _Target = value; }
    }
    private string _AuthorUserId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AuthorUserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AuthorUserId
    {
      get { return _AuthorUserId; }
      set { _AuthorUserId = value; }
    }
    private string _AuthorFIO;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"AuthorFIO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AuthorFIO
    {
      get { return _AuthorFIO; }
      set { _AuthorFIO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResolutionStatusType")]
    public enum ResolutionStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownResolutionStatus", Value=-1)]
      UnknownResolutionStatus = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Approved", Value=1)]
      Approved = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Disapproved", Value=2)]
      Disapproved = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ApprovementRequested", Value=3)]
      ApprovementRequested = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignatureRequested", Value=4)]
      SignatureRequested = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignatureDenied", Value=5)]
      SignatureDenied = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RevocationStatus")]
    public enum RevocationStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownRevocationStatus", Value=0)]
      UnknownRevocationStatus = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RevocationStatusNone", Value=1)]
      RevocationStatusNone = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RevocationIsRequestedByMe", Value=2)]
      RevocationIsRequestedByMe = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestsMyRevocation", Value=3)]
      RequestsMyRevocation = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RevocationAccepted", Value=4)]
      RevocationAccepted = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RevocationRejected", Value=5)]
      RevocationRejected = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoamingNotificationStatus")]
    public enum RoamingNotificationStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownRoamingNotificationStatus", Value=0)]
      UnknownRoamingNotificationStatus = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoamingNotificationStatusNone", Value=1)]
      RoamingNotificationStatusNone = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoamingNotificationStatusSuccess", Value=2)]
      RoamingNotificationStatusSuccess = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoamingNotificationStatusError", Value=3)]
      RoamingNotificationStatusError = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SenderSignatureStatus")]
    public enum SenderSignatureStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownSenderSignatureStatus", Value=0)]
      UnknownSenderSignatureStatus = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WaitingForSenderSignature", Value=1)]
      WaitingForSenderSignature = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SenderSignatureUnchecked", Value=2)]
      SenderSignatureUnchecked = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SenderSignatureCheckedAndValid", Value=3)]
      SenderSignatureCheckedAndValid = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SenderSignatureCheckedAndInvalid", Value=4)]
      SenderSignatureCheckedAndInvalid = 4
    }
  
}