//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Documents/GetDocumentsV4.proto
// Note: requires additional types generated from: Timestamp.proto
// Note: requires additional types generated from: CustomDataItem.proto
// Note: requires additional types generated from: TimeBasedFilter.proto
namespace Diadoc.Api.Proto.Documents
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDocumentsV4Request")]
  public partial class GetDocumentsV4Request : global::ProtoBuf.IExtensible
  {
    public GetDocumentsV4Request() {}
    
    private readonly global::System.Collections.Generic.List<string> _RecipientBoxId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"RecipientBoxId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> RecipientBoxId
    {
      get { return _RecipientBoxId; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _FromDepartmentId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"FromDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> FromDepartmentId
    {
      get { return _FromDepartmentId; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ToDepartmentId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ToDepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ToDepartmentId
    {
      get { return _ToDepartmentId; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _DepartmentId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"DepartmentId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DepartmentId
    {
      get { return _DepartmentId; }
    }
  

    private bool _ExcludeSubdepartments = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ExcludeSubdepartments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool ExcludeSubdepartments
    {
      get { return _ExcludeSubdepartments; }
      set { _ExcludeSubdepartments = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _DocumentTypeNamedId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"DocumentTypeNamedId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DocumentTypeNamedId
    {
      get { return _DocumentTypeNamedId; }
    }
  
    private string _DocumentCategory;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"DocumentCategory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DocumentCategory
    {
      get { return _DocumentCategory; }
      set { _DocumentCategory = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _DocumentStatus = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(8, Name=@"DocumentStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DocumentStatus
    {
      get { return _DocumentStatus; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _FileName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> FileName
    {
      get { return _FileName; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _DocumentNumber = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"DocumentNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DocumentNumber
    {
      get { return _DocumentNumber; }
    }
  

    private string _FromDocumentDate = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"FromDocumentDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FromDocumentDate
    {
      get { return _FromDocumentDate; }
      set { _FromDocumentDate = value; }
    }

    private string _ToDocumentDate = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ToDocumentDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ToDocumentDate
    {
      get { return _ToDocumentDate; }
      set { _ToDocumentDate = value; }
    }

    private Diadoc.Api.Proto.Timestamp _FromTimestamp = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"FromTimestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp FromTimestamp
    {
      get { return _FromTimestamp; }
      set { _FromTimestamp = value; }
    }

    private Diadoc.Api.Proto.Timestamp _ToTimestamp = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ToTimestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Diadoc.Api.Proto.Timestamp ToTimestamp
    {
      get { return _ToTimestamp; }
      set { _ToTimestamp = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _TotalSum = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"TotalSum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> TotalSum
    {
      get { return _TotalSum; }
    }
  

    private string _ToTotalSum = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ToTotalSum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ToTotalSum
    {
      get { return _ToTotalSum; }
      set { _ToTotalSum = value; }
    }

    private string _FromTotalSum = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"FromTotalSum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FromTotalSum
    {
      get { return _FromTotalSum; }
      set { _FromTotalSum = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem> _CustomData = new global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem>();
    [global::ProtoBuf.ProtoMember(18, Name=@"CustomData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.CustomDataItem> CustomData
    {
      get { return _CustomData; }
    }
  

    private Diadoc.Api.Proto.SortDirection _SortDirection = Diadoc.Api.Proto.SortDirection.Ascending;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"SortDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Diadoc.Api.Proto.SortDirection.Ascending)]
    public Diadoc.Api.Proto.SortDirection SortDirection
    {
      get { return _SortDirection; }
      set { _SortDirection = value; }
    }

    private int _Count = (int)100;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)100)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }

    private string _AfterIndexKey = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"AfterIndexKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AfterIndexKey
    {
      get { return _AfterIndexKey; }
      set { _AfterIndexKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}