on:
  push:
    paths-ignore:
      - "**/*.md"

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Build
        shell: pwsh
        env:
          DIADOC_SIGNING_SECRET: ${{ secrets.DIADOC_SIGNING_SECRET }}
        run: |
          & ./build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            bin/Release/DiadocApi.Nuget/*.nupkg
            bin/Release/*.zip
          if-no-files-found: error

  publish:
    runs-on: ubuntu-22.04
    needs: build_and_test
    if: startsWith(github.event.ref, 'refs/tags/version')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          files: |
            **/*.nupkg
            **/*.zip

      - name: Push NuGet package
        run: |
          dotnet nuget push "**/*.nupkg" --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_KEY }}
